version: '3.3'
services:
    app:
      image: a:latest
      network_mode: host
      restart: always
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"
          tag: "{{.Name}}"
